services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - ./data:/app/data

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - API_URL=http://api:8080
    depends_on:
      - api

volumes:
  data: