services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
    volumes:
      - ./data:/app/data
      - $HOME/.config/gcloud:/root/.config/gcloud

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    links:
      - api
    environment:
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - API_URL=api:8080
    depends_on:
      - api

volumes:
  data: