[tool.poetry]
name = "friday"
version = "0.1.0"
description = "A Python package to interact with Atlassian Jira, Google Vertex AI, Google GenAI, and other services."
license = "MIT"
authors = ["Dipjyoti Metia <dipjyotimetia@gmail.com>"]
readme = ["README.md", "LICENSE"]
keywords = ["atlassian", "jira", "google", "vertexai", "genai"]
package-mode = false

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.urls]
"Homepage" = "https://github.com/dipjyotimetia/friday"
"Bug Tracker" = "https://github.com/dipjyotimetia/friday/issues"

[tool.poetry.dependencies]
python = "^3.13"
langchain = "^0.3.13"
langchain-google-vertexai = "^2.0.9"
langchain-core = "^0.3.28"
google-cloud-aiplatform = "^1.75.0"
google-genai = "^0.5.0"
langchain-google-genai = "^2.0.7"
python-dotenv = "^1.0.1"
atlassian-python-api = "^3.41.16"
python-json-logger = "^3.2.1"
retrying = "^1.3.4"
langchain-community = "^0.3.14"
beautifulsoup4 = "^4.12.3"
pygithub = "^2.5.0"
chromadb = "^0.5.23"
langchain-chroma = "^0.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"

[tool.poetry.group.docs]
optional = true
dependencies = {}

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra -q"
testpaths = ["tests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
