name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install poetry
      uses: abatilo/actions-poetry@v4
      with:
        poetry-version: 'latest'
  
    - name: Cache poetry dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          .venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
  
    - name: Configure poetry
      run: |
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

    - name: Install dependencies
      run: poetry install --no-interaction  

    - name: Update version from tag
      run: |
        TAG=$(git describe --tags --abbrev=0)
        VERSION=${TAG#v}  # Remove 'v' prefix
        poetry version $VERSION
      shell: bash

    - name: Build and publish
      run: |
        poetry build
        poetry publish

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}