name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install toml

    - name: Install poetry
      uses: abatilo/actions-poetry@v4
      with:
        poetry-version: 'latest'
  
    - name: Cache poetry dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          .venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
  
    - name: Configure poetry
      run: |
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

    - name: Install dependencies
      run: poetry install --no-interaction  

    - name: Update version
      run: python scripts/update_version.py

    - name: Commit version update
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pyproject.toml
        git commit -m "chore: update version to $(git describe --tags --abbrev=0)"
        git push origin HEAD:main

    - name: Build and publish
      run: |
        poetry build
        poetry publish

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Homebrew Formula
      run: |
        # Get latest version
        VERSION=$(git describe --tags --abbrev=0)
        
        # Calculate SHA256 of tar.gz
        wget https://github.com/dipjyotimetia/friday/archive/refs/tags/$VERSION.tar.gz
        SHA=$(sha256sum $VERSION.tar.gz | cut -d' ' -f1)
        
        # Clone homebrew tap repo with token auth
        git clone "https://oauth2:${HOMEBREW_TOKEN}@github.com/dipjyotimetia/homebrew-friday.git"
        cd homebrew-friday
        
        # Update formula
        sed -i "s/\[LATEST_VERSION\]/$VERSION/" friday.rb
        sed -i "s/\[SHA256_OF_TAR\]/$SHA/" friday.rb
        
        # Commit and push
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add friday.rb
        git commit -m "Update to version $VERSION"
        git push
      env:
        HOMEBREW_TOKEN: ${{ secrets.HOME_BREW_TOKEN }}    