name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  py-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install toml

    - name: Install poetry
      uses: abatilo/actions-poetry@v4
      with:
        poetry-version: 'latest'
  
    - name: Cache poetry dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          .venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
  
    - name: Configure poetry
      run: |
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

    - name: Install dependencies
      run: poetry install --no-interaction  

    - name: Update version
      run: python scripts/update_version.py

    - name: Generate requirements.txt
      run: |
        poetry export -f requirements.txt --output requirements.txt --without-hashes
        if [ $? -ne 0 ]; then
          echo "Failed to generate requirements.txt"
          exit 1
        fi

    - name: Commit version update
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pyproject.toml requirements.txt src/friday/version.py
        
        # Only commit if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "chore: update version to $(git describe --tags --abbrev=0)"
          git pull --rebase origin main
          git push origin HEAD:main
        fi

    - name: Build and publish
      run: |
        poetry build
        poetry publish

    - name: Create Cli Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  app-build:
    needs: py-release
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install Dependencies
        working-directory: ./app
        run: |
          npm ci
          npm run rebuild

      - name: Build & Release
        working-directory: ./app
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifacts
          path: app/dist/
          if-no-files-found: error

  app-release:
    needs: app-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: '*-artifacts'
          merge-multiple: true

      - name: Create App Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-homebrew:
    needs: py-release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main

    - name: Update Homebrew Formula
      run: |
        VERSION=$(git describe --tags --abbrev=0)
        TARBALL_URL="https://github.com/dipjyotimetia/friday/archive/refs/tags/${VERSION}.tar.gz"
        
        # Clone homebrew-friday repository
        git clone https://github.com/dipjyotimetia/homebrew-friday.git
        cd homebrew-friday
        
        # Download and calculate SHA
        curl -L -o release.tar.gz $TARBALL_URL
        SHA=$(sha256sum release.tar.gz | cut -d' ' -f1)
        
        # Update formula
        sed -i "s|url.*|url \"$TARBALL_URL\"|" Formula/friday.rb
        sed -i "s|sha256.*|sha256 \"$SHA\"|" Formula/friday.rb
        
        if [ -n "$(git status --porcelain)" ]; then
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Formula/friday.rb
          git commit -m "chore: update friday formula to version ${VERSION}"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/dipjyotimetia/homebrew-friday.git main || {
            echo "Failed to push changes"
            exit 1
          }
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.HOME_BREW_TOKEN }}
